name: Build examples for an ESP-IDF project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version:
          # version from https://hub.docker.com/r/espressif/idf/tags
          - v5.3.2
          - v5.4.1
          - release-v5.5
          - latest

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: esp32
        path: extras/idf_project_example
  
